### ISSUE TITLE
css wrap class issue

### ISSUE THREAD

**Issue by warlof** [ciaa-cnam/STOFMA#11]
What is the wrap class purpose ?

It forces the page height to the screen height and display an uggly end page layout before the real page's end.

![image](https://cloud.githubusercontent.com/assets/648753/9524246/3508f588-4cde-11e5-8afc-6bb3913781b5.png)

**Comment by edimitchel** [comment]
It will be fix by next commits. Thanks.

**Comment by FWoelffel** [comment]
I thought this was intended.
Also, IMO, the aesthetic aspects of the client should results in issues. Should I also open one because I think that the colour choices are wrong. Should I open an issue ? No.
