### ISSUE TITLE
Orders history target ?

### ISSUE THREAD

**Issue by warlof** [ciaa-cnam/STOFMA#12]
Why orders are removable or editable ?
In my sense, they should not.

The app needs to keep in memory the history of what has been done and in this purpose, we shouldn't be able to remove or edit past orders.

**Comment by fwoelffel** [comment]
What if there is a mistake in the orders you created ? How would you handle it ?

**Comment by warlof** [comment]
If products are missing, you can make a new order.
if there are too much, you credit the account and the stock with the difference ?

Or instead removing the order, tell a button to do the logic upper and remove edit/remove buttons.

**Comment by fwoelffel** [comment]
What do you mean by "order" ? Actually there is two kinds of order entities :
- Sales, which are set up between the stock and a customer
- Purchase, which are set up between some store and the stock

Are you saying that we could correct mistakes related to _quantities_ by adding reverse orders ? That could do the trick but I don't think it is a proper way to handle this. Whatever, let's imagine we handle errors related to quantities like this. How would you handle mistakes related to dates, customers, products, etc. ?

**Comment by warlof** [comment]
I was talking about sales but both should be managed by the same way.

"Are you saying that we could correct mistakes related to quantities by adding reverse orders"

It what is done in business, if you make a mistake with a product quantity or order amount, you create a new "ticket" with negative entries.

So you can now that, on a specific date, you made an order with some kind products amount for some money amount.
And on another date, you made a corrective entry with new kind of products and money amount.

The goal is to keep a stack about what is done on each action.

**Comment by fwoelffel** [comment]
Ok, now I get it. I partially agree with you.
Your solution offers a nice way to keep a trace of all edits. On the other hand, this could also be done by logging all operations. Plus, I don't think that this solution is as user-friendly as a simple update form.

**Comment by warlof** [comment]
mmh, not false.

**Comment by guillermau** [comment]
![kaamelott7](https://cloud.githubusercontent.com/assets/4137884/9542184/d48dfe38-4d6e-11e5-81b7-fcaa9dca2586.jpg)
