### ISSUE TITLE
Load depending on scroll position

### ISSUE THREAD

**Issue by warlof** [ciaa-cnam/STOFMA#13]
I saw that you would avoid to load an huge list for products, orders or whatever.

It's possible to make them loadable dependent on the scroll position.
The principe is simple, you paginate your data, on the page load, you call for the first page, and when the user scroll, you make N calls in order to get N pages appended to the list.

Since you're using angular, i've found a library which do that https://sroze.github.io/ngInfiniteScroll/

**Comment by edimitchel** [comment]
This problematic isn't for product but purchases or sales. I will consider this asap.

**Comment by corentindesfarges** [comment]
Already planned in the product backlog.
