### ISSUE TITLE
Interface enhancement

### ISSUE THREAD

**Issue by edouard-mangel** [ciaa-cnam/STOFMA#14]
Hello, 

Your scrollbar to choose user is quite nice when you have few users, but is not suited to a list of dozens of items. In addition, according to whom you are selling a product, the price isn't supposed to be the same. So how about selecting the user first, in order to improve user experience. 

This option would allow you to: 
- choose any action regarding the person and reducing the risk of errors, 
- display the product prices according to the user's status, 
- display the user's account before selecting products, hence knowing before typing the basket if the user has enough money on his/her account.

**Comment by edimitchel** [comment]
We made decision to implement this cinematic and will implement it soon.
