### ISSUE TITLE
"Sign in" on Firefox and Safari

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#19]
I wanted to try the application on Firefox and Safari...

~~On Safari on Windows, the style sheet seems broken...
Deleted image.~~
**EDIT : Probably caused by JS (not activated).**

On Safari and Firefox, the sign up form doesn't work (it does nothing).

**Comment by edimitchel** [comment]
Waow ! I didn't have this on my navigators (Safari and Firefox on OSX 10.10.5) !

Please, check if javascript is enable and the network panel in developer tools.

**Comment by corentindesfarges** [comment]
I confirm that JS is activated on Firefox (Ubuntu and Windows) and nothing happened when I click to validate the creation of a new account.

There is nothing in the Network tab of the dev tool :
![capture du 2015-08-31 09 45 46](https://cloud.githubusercontent.com/assets/5452616/9574234/23890156-4fc5-11e5-8afb-7628fdccf8ae.png)
And nothing in the console...

**Comment by edimitchel** [comment]
Hum.. I don't see any javascript file downloaded.. Strange.. Can you send me a capture of the console panel ?

**Comment by corentindesfarges** [comment]
![capture du 2015-08-31 09 57 56](https://cloud.githubusercontent.com/assets/5452616/9574395/c6de3d20-4fc6-11e5-9987-736342a757ec.png)

**Comment by edimitchel** [comment]
What is your Firefox version ?

**Comment by corentindesfarges** [comment]
The last version, 40.0.3 (for Linux Mint), and the last version too on Windows.

**Comment by corentindesfarges** [comment]
The issue comes from the birth date field... On Chrome, the expected fomat is "dd/mm/yyyy", and Firefox seems expect "yyyy-mm-dd". Can you fix it ?

**Comment by edimitchel** [comment]
Yep, I will fix it!
