### ISSUE TITLE
Not enough items

### ISSUE THREAD

**Issue by edimitchel** [ciaa-cnam/STOFMA#27]
When I do a sale, I have 407 HTTP error **Not enough items** while product have enough stock. 

For example: 
It leaves 1 bottle of water, I select one for selling it. I confirm et got error..

![image](https://cloud.githubusercontent.com/assets/2922851/9601437/cdba1ee4-50a1-11e5-8fbc-17af9b263594.png)

![image](https://cloud.githubusercontent.com/assets/2922851/9601445/db23a5c8-50a1-11e5-8433-a128c1f1c3a4.png)

![image](https://cloud.githubusercontent.com/assets/2922851/9601450/e5a9a98e-50a1-11e5-9097-a5d5aa7dfe43.png)

![image](https://cloud.githubusercontent.com/assets/2922851/9601453/f1e2bae2-50a1-11e5-8895-cc23979d2684.png)
The message of this alert error is inappropriate but it's not the problem.

**Comment by corentindesfarges** [comment]
Can you reproduce this bug with another customer, or is it specific for the guest member ? Can you reproduce the bug without your uncommitted changes ?

**Comment by edimitchel** [comment]
This bug occurs independently the selected customer / guest.

**Comment by corentindesfarges** [comment]
And without your local changes?

**Comment by edimitchel** [comment]
I don't try without my local changes it but I thinking the problem is on the api side : Data sended are good but not the response.

![image](https://cloud.githubusercontent.com/assets/2922851/9602444/f0049a0e-50a8-11e5-807d-56c7732cf8c7.png)

![image](https://cloud.githubusercontent.com/assets/2922851/9602454/fa0767de-50a8-11e5-871c-efca4d9f27f6.png)

**Comment by edimitchel** [comment]
For test, I did a sale of **X-1** products while his stock is **X**, and it _works_ !
But when I did a sale of **X** products, it _fails_.
