### ISSUE TITLE
Empty lists

### ISSUE THREAD

**Issue by fwoelffel** [ciaa-cnam/STOFMA#3]
When there is no items to show, the list elements still enabled. I don't think they should.
![screen shot 2015-08-25 at 19 07 00 2](https://cloud.githubusercontent.com/assets/5467696/9473704/90545492-4b5c-11e5-8aaf-0c22822dc9bc.png)
How to reproduce this misbehaviour:
- Install a new instance of STOFMA
- Log in with the default admin account
- Open a list element supposed to show products, sales, etc. (anything not existing yet)

**Comment by edimitchel** [comment]
Ok, I change it fastly.

**Comment by fwoelffel** [comment]
Same misbehaviour when managing roles with no other users created.
![screen shot 2015-08-25 at 19 48 45 2](https://cloud.githubusercontent.com/assets/5467696/9474696/7a077330-4b62-11e5-99be-784c4d9867f8.png)
