### ISSUE TITLE
Wrong account statement

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#32]
As you can see below, the values are wrong.
![image](https://cloud.githubusercontent.com/assets/5452616/9647556/9c51e754-51de-11e5-85b8-57d2f5759072.png)

The problem comes from the unit tests, and I didn't success to reproduce it with the GUI. Maybe it comes from update of sales or pruchases (GUI is missing).

I investigate about it.

**Comment by fwoelffel** [comment]
Which controller is supposed to compute these values ?

**Comment by corentindesfarges** [comment]
These values are computed directly by the client.
