### ISSUE TITLE
Move some menus

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#33]
To save space on the left side of the application, can you put the "Accueil" menu and "Paramètres" menu next to the logout button? Because in administrator mode, I have an ugly scrollbar for the menu, and they are not the main menus in my opinion.

![image](https://cloud.githubusercontent.com/assets/5452616/9656802/8691dbe2-523b-11e5-9aa0-5b468779d866.png)

**Comment by edimitchel** [comment]
About "Paramètres" menu, I think it's an useless menu for this time bing. I'll hide it.

I agree with your opinion ;)
