### ISSUE TITLE
Create/Update a product with member price to 0 doesn't take it.

### ISSUE THREAD

**Issue by edimitchel** [ciaa-cnam/STOFMA#34]
When the member price for a product equals 0 is submitted (creating or updating), it's ignored.

Not really important but we can fix for member a free price for a special product.

**Comment by edouard-mangel** [comment]
Wouldn't it be better to automatically set the price for the members equal
to the price for non members automatically, and provide the ability to
change it later?

2015-09-03 23:49 GMT+02:00 Michel EDIGHOFFER notifications@github.com:

**Comment by edimitchel** [comment]
It's already implemented ! The problem is when we want to put 0 to the member price.

**Comment by corentindesfarges** [comment]
It sounds that the issue comes from the client. When I save the change, two requests are sent. Can you check that ?
