### ISSUE TITLE
Cannot select a product during add of purchase

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#36]
We cannot choose a product when we create a purchase. The list with autocomplete isn't displayed.
![capture du 2015-09-04 11 25 51](https://cloud.githubusercontent.com/assets/5452616/9680585/1123452c-52f8-11e5-8182-86593a8b3b08.png)

**Comment by edimitchel** [comment]
Have you type few letter ?

This error isn't the source of this problem.

**Comment by corentindesfarges** [comment]
It sounds me that this issue has been fixed with a previous commit. I get this error on the @FWoelffel server, which is not up-to-date.

**Comment by fwoelffel** [comment]
Indeed, a pull fixed this issue on our server.
