### ISSUE TITLE
Plugin not loaded before refresh page

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#39]
I'm working on the new experimental branch (**experimental_plugins**). When I start the server, and just before the connection, the **role** plugin isn't loaded. As if the application doesn't find the JS file : 
![image](https://cloud.githubusercontent.com/assets/5452616/9704542/98c8beb2-54ab-11e5-9c7b-7e8a3fc9c4a6.png)

The most suprising is when I refresh the page, the plugin is loaded...

To reproduce this issue : 
- git checkout experimental_plugins
- sails lift
- _connection with administrator account_

**Comment by edimitchel** [comment]
No problem on my side.

Clear navigator cache with `Ctrl-Shift+R`.
