### ISSUE TITLE
Sale canceled for invited member

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#4]
The server crashes when I try to sell a product to an invited member. The sale has to be saved specifically, because the money doesn't come from any credit account (in cash for example).
This could represent an opportunity for us to add other ways to pay (from the account, with cash, check...) ?

**Comment by edimitchel** [comment]
Hum.. It is normal. 
The API should implement a special role for invited members. With that, I can specify the member (existing in database) and this issue _will be no longer_.

Waiting decision for implementing.

**Comment by corentindesfarges** [comment]
Closed by [this commit](https://github.com/ciaa-cnam/STOFMA/commit/9ee0e1a348076d0cbcfc640d048147a580e5c0fc).
