### ISSUE TITLE
Time of datetime not saved

### ISSUE THREAD

**Issue by edimitchel** [ciaa-cnam/STOFMA#40]
It looks like that on production **postgresql** doesn't care about time. It's important to know the exact time. Be careful because time must in the UTC format. (+0200 for France).

Example :
<img width="520" alt="capture d ecran 2015-09-08 a 02 32 22" src="https://cloud.githubusercontent.com/assets/2922851/9724075/e9414b44-55d1-11e5-8f28-e3f1a906546b.png">

**Comment by fwoelffel** [comment]
Can @corentindesfarges tell us if he encountered the same behaviour on LocalDiskDB?

**Comment by corentindesfarges** [comment]
No, we don't have this issue on LocalDiskDB.

**Comment by edimitchel** [comment]
Ok nice but bad issue...
