### ISSUE TITLE
Strange field in the bottom page

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#41]
When I update an user, I get this :

![capture du 2015-09-17 14 57 25](https://cloud.githubusercontent.com/assets/5452616/9933633/75b95766-5d4c-11e5-8023-1d8107d70fc4.png)

But the update is done...

**Comment by edimitchel** [comment]
This problem seems present only in production. The grunt tasks didn't take stylesheets of sweetAlert.
