### ISSUE TITLE
"npm test" dropped production database

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#6]
When I run "npm test", the database is dropped, and all the data are lost.

It could be really interesting to put the data from unit tests in another database (in memory by example) and to save the data from production in something like MongoDB, or CouchDB.

**Comment by fwoelffel** [comment]
I think using the memory adapter for tests could solve this issue. Plus, it surely will reduce the tests duration. I'll take care of that asap.
