### ISSUE TITLE
Need forms to update purchase and sale

### ISSUE THREAD

**Issue by corentindesfarges** [ciaa-cnam/STOFMA#7]
It seems that the API already allows to update a sale and a purchase (the unit tests about it are passed!), but we need to do it from the application, with a GUI.

**Comment by warlof** [comment]
+1
Have a cart for sale and purchase on which display details and edit form could be great.

**Comment by corentindesfarges** [comment]
This issue is not about cart. I just need a form to update sale and purchase.
By the way, @edimitchel is already working on this point.

**Comment by warlof** [comment]
I would meen "card" instead "cart"
Keyboard issue :s

**Comment by edimitchel** [comment]
What do you mean by "card" ? I don't understand..

**Comment by warlof** [comment]
As corentin said : a form which will be use in order to display or update data from a specific record.
